<?php

namespace Drupal\ibew_contractor_map\Service;

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\node\NodeInterface;
use Drupal\Component\Utility\Html;

/**
 * Service to fetch and sanitize contractor data for the map.
 */
class ContractorDataService
{

    /**
     * The entity type manager.
     *
     * @var \Drupal\Core\Entity\EntityTypeManagerInterface
     */
    protected $entityTypeManager;

    /**
     * ContractorDataService constructor.
     *
     * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager
     *   The entity type manager.
     */
    public function __construct(EntityTypeManagerInterface $entity_type_manager)
    {
        $this->entityTypeManager = $entity_type_manager;
    }

    /**
     * Get contractor data for the map.
     *
     * @return array
     *   Array of sanitized contractor data including coordinates.
     */
    public function getContractorData()
    {
        $contractors = [];

        // Query for published contractor profiles with coordinates.
        $query = $this->entityTypeManager
            ->getStorage('node')
            ->getQuery()
            ->accessCheck(FALSE)
            ->condition('type', 'contractor_profile')
            ->condition('status', NodeInterface::PUBLISHED);

        $nids = $query->execute();

        if (!empty($nids)) {
            $nodes = $this->entityTypeManager
                ->getStorage('node')
                ->loadMultiple($nids);

            foreach ($nodes as $node) {
                /** @var \Drupal\node\NodeInterface $node */
                // Get coordinate values.
                $lat = $node->get('field_latitude')->value;
                $lng = $node->get('field_longitude')->value;

                // Only add contractors with coordinates.
                if ($lat && $lng) {
                    $address = '';
                    $street = $node->get('field_street_address')->value;
                    $city = $node->get('field_city')->value;
                    $state = $node->get('field_state')->value;
                    $zip = $node->get('field_zip')->value;

                    if ($street || $city || $state || $zip) {
                        $address_parts = array_filter([$street, $city, $state, $zip]);
                        $address = implode(', ', $address_parts);
                    }

                    $phone = $node->get('field_phone')->value;
                    $website = $node->get('field_website')->uri;

                    // Get image URL if available.
                    $image_url = '';
                    $image_field = $node->get('field_image');
                    if (!$image_field->isEmpty()) {
                        $image_item = $image_field->first();
                        if ($image_item) {
                            $image_entity = $image_item->entity;
                            if ($image_entity) {
                                // Ensure the URL is absolute or root-relative as needed
                                // createFileUrl() returns a root-relative string usually.
                                // We should sanitize user inputs, but image URL is generated.
                                // Still good practice to make sure it's safe.
                                $image_url = $image_entity->createFileUrl();
                            }
                        }
                    }

                    // Build the array, escaping all user-generated content.
                    $contractors[] = [
                        'id' => $node->id(),
                        'title' => Html::escape($node->getTitle()),
                        'lat' => (float) $lat, // Cast to float is safe
                        'lng' => (float) $lng, // Cast to float is safe
                        // Address parts are user input
                        'address' => Html::escape($address),
                        // Phone is user input
                        'phone' => Html::escape($phone),
                        // Website is user input, but usually validated as URL. 
                        // Still, escaping attributes is safer if used in href.
                        // However, Html::escape() escapes quotes and ampersands.
                        // If used in href="..." it should be fine.
                        'website' => Html::escape($website),
                        // Image URL is generated by system, but let's be safe
                        'image' => $image_url,
                    ];
                }
            }
        }

        return $contractors;
    }

}
